### ISSUE TITLE
Actividad 7 Reporte de Cuestionario

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-hjfs#1]

**Comment by FedericoVictorianoSierra** [comment]
[Práctica 7 Entrevista (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-hjfs/files/9856891/Practica.7.Entrevista.Federico.Victoriano.Sierra.pdf)

**Comment by JoseABCruz** [comment]
[Práctica 7 Cuestionario (Jose Antonio Balbuena Cruz 5US).pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-hjfs/files/9856897/Practica.7.Cuestionario.Jose.Antonio.Balbuena.Cruz.5US.pdf)

**Comment by Heidi-19** [comment]
[Práctica 7 Entrevista-Heidi Lucy Bautista Sanjuan 5USC.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-hjfs/files/9860182/Practica.7.Entrevista-Heidi.Lucy.Bautista.Sanjuan.5USC.pdf)

**Comment by EdwinOrtiz1412** [comment]
calificacion: 30

**Comment by SANDRAVELASCO** [comment]
[Práctica 7 Entrevista.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-hjfs/files/9956426/Practica.7.Entrevista.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
